name: Sync Vcmi
on:
  schedule:
    - cron: '0 1 2 * *'
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/re_sync_fork_remote.yml
    with:
      repo: "vcmi"
      branch: "develop"
      event_name: ${{ github.event_name }}
    secrets: inherit
    
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: pass or fail
        run: |
          echo ${{ needs.job1.outputs.message }}
          echo ${{ needs.job1.outputs.result }}
