name: test checkout and push
# 必须设置 permissions：Read and write permissions
on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: update 
        run: |
          git remote -v
          echo "test checkout and push" >> test.txt
          git status
          git config --global user.email "${{ github.actor }}"
          git config --global user.name "${{ github.actor }}@github.com"
          git add .
          git commit -m'test checkout and push'
          git push
          git status

          
          
